# Generated by Django 4.0.5 on 2022-06-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pedido_alter_ativo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='checkbox',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precocompra',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precovenda',
        ),
    ]
