# Generated by Django 4.0.5 on 2022-06-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_pedido_checkbox_remove_pedido_duracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
