# Generated by Django 4.0.5 on 2022-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pedido_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ativo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mercado',
            field=models.CharField(max_length=20),
        ),
    ]
