# Generated by Django 4.0.5 on 2022-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pedido_ativo_alter_pedido_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='periodo',
            field=models.IntegerField(default=15),
        ),
    ]
