# Generated by Django 4.0.5 on 2022-06-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pedido_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precovenda',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=6),
        ),
    ]
