# Generated by Django 4.0.5 on 2022-06-15 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pedido_precocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
