# Generated by Django 4.0.5 on 2022-06-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mercado', models.TextField(max_length=20)),
                ('ativo', models.TextField(max_length=20)),
                ('precocompra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precovenda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periodo', models.IntegerField()),
                ('duracao', models.IntegerField()),
                ('checkbox', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='ativo',
            options={'ordering': ['ticker']},
        ),
    ]
